[package]
name = "hyperloglog"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"

[dependencies.xxhash-rust]
version = "0.8.12"
features = ["xxh3", "const_xxh3"]